title: LuHopeTest
description: This is a just test for docs
theme: just-the-docs

url: https://33-Hope.github.io/DocsTemplate

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
